// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGRE.ERP.Web.Components.Services;

#nullable disable

namespace RGRE.ERP.Web.Migrations
{
    [DbContext(typeof(WebAuthDbContext))]
    partial class WebAuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RGRE.ERP.Web.Components.Services.PersistedAuthTicket", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AuthTickets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
